services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: db_node
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: node_app
    restart: unless-stopped
    depends_on:
      - db
    entrypoint: >
      sh -c "echo 'Menunggu MySQL…';
             until nc -z db 3306; do sleep 1; done;
             echo 'MySQL ready!';
             npm run dev"
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER:-appuser}
      DB_PASS: ${DB_PASS:-apppass}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      REFRESH_SECRET: ${REFRESH_SECRET}
    ports:
      - "3000:3000"

volumes:
  db_data:
